# Cloudflare Pages 构建配置
# 将此文件重命名为 _build_config.yaml 并推送到仓库根目录
# 或者直接在 Cloudflare Pages 控制台设置

build:
  command: npm run build:cloudflare
  publish: dist
  
# 环境变量
env:
  NODE_VERSION: "18"
  NPM_VERSION: "8"

# 重定向和头部文件
include:
  - "_redirects"
  - "_headers"
