name = "sparklog"
compatibility_date = "2024-01-01"

# Cloudflare Pages 配置
[build]
command = "npm run build:pages"
cwd = "."

# 构建输出目录配置（Cloudflare Pages 专用）
[pages]
pages_build_output_dir = "dist"

# 环境配置
[env.production]
name = "sparklog-prod"

[env.staging]
name = "sparklog-staging"

# 环境变量（敏感信息通过 Cloudflare 控制台设置）
[vars]
NODE_ENV = "production"
BUILD_VERSION = "1.0.0"
