name = "sparklog"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# 构建配置
[build]
command = "npm run build:pages"
watch_dir = "src"
cwd = "."

# 构建钩子配置
[build.hooks]
pre_build = "npm run pre-build"
post_build = "npm run post-build"

# 环境配置
[env.production]
name = "sparklog-prod"
route = "sparklog.wiki-power.com/*"

[env.staging]
name = "sparklog-staging"
route = "staging.sparklog.wiki-power.com/*"

# 环境变量（敏感信息通过 Cloudflare 控制台设置）
[vars]
NODE_ENV = "production"
BUILD_VERSION = "1.0.0"

# 自定义域名配置
[[env.production.routes]]
pattern = "sparklog.wiki-power.com/*"
zone_name = "wiki-power.com"

# 构建输出配置
[build.upload]
format = "service-worker"
